version: 1.0.{build}
install:
  - ps: .\install.ps1
build_script:
  - ps: .\build.ps1
  - nuget pack FFmpeg.Nightly.nuspec
  - ps: Get-ChildItem . *.nupkg | foreach { & nuget add $_ -Source localfeed }
  - nuget restore -Source "%cd%\localfeed"
  - msbuild ffmpeg-nuget.sln /p:Configuration=Debug /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - msbuild ffmpeg-nuget.sln /p:Configuration=Release /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - msbuild ffmpeg-nuget.sln /p:Configuration=Debug /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
  - msbuild ffmpeg-nuget.sln /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
test_script:
  - ps: |
      Push-Location Release
      ..\test.ps1
      Pop-Location
      Push-Location Debug
      ..\test.ps1
      Pop-Location
      Push-Location x64\Release
      ..\..\test.ps1
      Pop-Location
      Push-Location x64\Debug
      ..\..\test.ps1
      Pop-Location
after_test:
  - 7z a testresults.zip Release\test.* Debug\test.* x64\Release\test.* x64\Debug\test.*
artifacts:
  - path: '*.nupkg'
  - path: testresults.zip
deploy:
  provider: NuGet
  api_key:
    secure: +eaRtuS8FIOb86osYZasM+ZoAv/569NG1sMoK08rCTzo67s5r/e1FTgoCrIOTvOK
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
