version: 1.0.{build}
install:
  - ps: .\install.ps1
build_script:
  - ps: .\build.ps1
  - nuget pack FFmpeg.Nightly.nuspec
  - msbuild ffmpeg-nuget.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
  - path: '*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: +eaRtuS8FIOb86osYZasM+ZoAv/569NG1sMoK08rCTzo67s5r/e1FTgoCrIOTvOK
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
